### ISSUE TITLE
Please give credit to the repo you sourced your code from

### ISSUE THREAD

**Issue by sdporres** [AdamEC/Unity-Trello#3] opened 2019-05-01 03:47 UTC
Which is https://github.com/bfollington/Trello-Cards-Unity

**Comment by AdamCarballo** [comment] 2019-05-01 05:27
Hey, the credit has been always there in the README, under License and History. It's also present in some of the script files as a comment. I've even communicated with him in the past.

Closing, not sure where the issue is, sorry.

**Closed as completed by AdamCarballo** 2019-05-01 05:27 UTC
